name: Go Tests 

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20', ]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: make install-server
      - name: Create env file
        run: |
          touch server/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> server/.env
      - name: Run Go Tests
        run: make test-server 
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json
